---
- hosts: all
#  vars_prompt:
#    - name: "mysql_root_password"
#      prompt: "Please choose a root password for mySQL installation"
#      private: yes
  tasks:
    - name: Install needed mySQL and python packages.
      become: true
      become_user: root
      become_method: sudo
      apt: name={{item}} state=present update_cache=yes
      with_items:
           - mysql-client
           - python-m2crypto
           - python-mysqldb
           - python-docker

    - name: Pick a random password for root user.
      shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 20
      register: passgen1

    - set_fact: mysql_root_password="{{ passgen1.stdout }}"

    - name: Disclose password.
      debug: msg="The mysql root password is {{ mysql_root_password }}."

    - name: Pick a random password for normal user.
      shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 20
      register: passgen2

    - set_fact: mysql_user="{{ ansible_user_id }}"
    - set_fact: mysql_user_password="{{ passgen2.stdout }}"

    - name: Disclose password.
      debug: msg="The mysql user is {{ mysql_user }} and password is {{ mysql_user_password }}."

    - name: Create mySQL docker container
      become: true
      become_user: root
      become_method: sudo
      docker_container:
        name: stats-mysql
        image: mysql/mysql-server
        state: stopped
        ports:
          "3306:3306"
        env:
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_DATABASE: "protogeniHistory"
          MYSQL_PASSWORD: "{{ mysql_user_password }}"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_ROOT_HOST: "%"

    - name: Create mySQL config file (.my.cnf).
      template:
        src: my.cnf.j2
        dest: "{{ ansible_env.HOME }}/.my.cnf"
        mode: 0600

    - name: Grab mySQL config file.
      shell: docker cp stats-mysql:/etc/my.cnf /tmp
      register: get-my-cnf

    - name: Update mySQL config.
      lineinfile: 
        path: /tmp/my.cnf
        line: "default-authentication-plugin=mysql_native_password"
        insertafter: "#default-authentication-plugin"

    - name: Replace mySQL config in container.
      shell: docker cp /tmp/my.cnf stats-mysql:/etc
      register: put-my-cnf

    - name: Start mySQL container.
      shell: docker start stats-mysql
      register: mysql-start


        #    - name: Initialize ProtoGENI history database in mySQL.
        #      command: mysql --database=mysql --execute="create database protogeniHistory;"
        #      register: command_result
        #      retries: 10
        #      delay: 10
        #      until: command_result is success

        #    - name: Initialize historyRecords table.
        #      shell: mysql < "{{ ansible_env.HOME }}/statistics/ProtoGENIHistoryAnalysis/initializeRecordsTable.sql"

    
